name: build_and_deploy
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
jobs:
  build_frontend:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: checkout
        uses: actions/checkout@v2
      # Get Node
      - name: get node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install client
        working-directory: ./client
        run: npm ci
      - name: build client
        working-directory: ./client
        run: npm run build
      - name: install cdk
        working-directory: ./infrastructure
        run: npm ci
      # deploy cdk
      - name: deploy
        working-directory: ./infrastructure
        run: npm run cdk:deploy -- --require-approval never
